name: Generate Recipe Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Git
        uses: actions/setup-node@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Install dependencies
        run: |
          apt-get update
          # Update pip
          python3 -m pip install --upgrade pip
          # Install other dependencies from requirements.txt
          pip3 install -r scripts/requirements.txt

      - name: Set environment variable
        run: echo "STORE_NAME=metro" >> $GITHUB_ENV

      - name: Run Python Script
        run: |
          python3 scripts/generate_recipe.py

      - name: Commit and push if it changed
        run: |
          git diff
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/*
          git commit -m "Pushing scraped data." -a || echo "No changes to commit"
          git pull origin main --rebase
          git push origin main
