name: Generate Recipe Action

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Git and Install dependencies
        run: |
          # Update pip
          python3 -m pip install --upgrade pip
          # Install other dependencies from requirements.txt
          pip3 install -r scripts/requirements.txt

  generate_recipe:
    runs-on: self-hosted
    needs: setup
    strategy:
      matrix:
        store: [metro, foodbasics]
        attempt: [1, 2]

    steps:
      - name: Set environment variable
        run: echo "STORE_NAME=${{ matrix.store }}" >> $GITHUB_ENV

      - name: Run Python Script
        run: |
          python3 scripts/generate_recipe.py

  commit_changes:
    runs-on: self-hosted
    needs: generate_recipe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Git
        run: |
        
          # Update pip
          python3 -m pip install --upgrade pip
          
      - name: Commit and push all changes
        run: |
          git diff
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/*
          git commit -m "Pushing all generated data" -a || echo "No changes to commit"
          git pull origin main --rebase
          git push origin main
