name: Generate Image Action

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 4"  # Run every Thursday at 7 AM (EST)

jobs:
  generate-image:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}       
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          # Update pip
          python3 -m pip install --upgrade pip
          # Install other dependencies from requirements.txt
          pip3 install -r scripts/requirements.txt

      
      - name: Run Python Script
        env:
          PROMPT: "Watermelon Pie"
          RECIPE_ID: "1004"
        run: |
          python3 scripts/generate_image.py


      - name: Commit and push if it changed
        run: |
          git diff
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/*
          git commit -m "Pushing scraped data." -a || echo "No changes to commit"
          git pull origin main --rebase
          git push origin main
