name: Generate Image Action

on:
  workflow_dispatch:

jobs:
  generate-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
          sudo apt-get install -y google-chrome-stable
          python3 -m pip install --upgrade pip
          pip3 install selenium webdriver_manager

      - name: Run Python Script
        env:
          PROMPT: "Watermelon Pie"
          RECIPE_ID: "1004"
        run: |
          python3 scripts/generate_image.py

      - name: Commit and push if it changed
        run: |
          git diff
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/*
          git commit -m "Pushing scraped data." -a || echo "No changes to commit"
          git pull origin main --rebase
          git push origin main
