name: Request Recipes OpenAI
on:
    workflow_dispatch:
    workflow_run:
        workflows: ['Clean Data']
        types: [completed]
        branches:
            - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
          token: ${{ secrets.PAT }}
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: '3.x'

    - name: Install dependencies
      run: pip install openai python-dotenv
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(TZ=America/Toronto date +'%Y%m%d')"

    - name: Run script metro
      env: 
        JSON_FORMAT: scripts/jsonForamt.json
        RECIPE_NUMBER: 7
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} #should be declared in secrets
        DATA_FILE_PATH: data/scrapedData/metro/metro_${{ steps.date.outputs.date }}.csv
        RECIPE_FILE_PATH: data/requestedRecipes
        DIET_TYPE: normal
        STORE_NAME: metro
        CURRENT_DATE: ${{ steps.date.outputs.date }}
        DELAY_TIME: 90000
      run: python scripts/requestRecipesNode.py
      
    - name: Commit and push if it changed
      run: |
        git diff
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/*
        git commit -m "Pushing Recipes" -a || echo "No changes to commit"
        git pull origin main --rebase
        git push origin main
