name: Request Recipes OpenAI
on:
    workflow_dispatch:
    workflow_run:
        workflows: ['Clean Data']
        types: [completed]
        branches:
            - 'main'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
          token: ${{ secrets.PAT }}
    
    - name: Set up Nodejs
      uses: actions/setup-node@v2
      with: 
        node-version: '20'

    - name: Install dependencies
      run: npm install openai dotenv fs module path
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"

    - name: Run script
      env: 
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} #should be declared in secrets
        CSV_FILE_PATH: data/scrapedData/metro/metro_${{ steps.date.outputs.date }}.csv
        ASSISTANT_ID: asst_x4VQbYi72W6pgafutM97jqrT # should be placed in secrets
        DIET_TYPE: vegetarian
        STORE_NAME: metro
        DELAY_TIME: 90000
      run: node scripts/requestRecipesNode.js
      
    - name: Commit and push if it changed
      run: |
        git diff
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add scrapedData/*
        git commit -m "Pushing Recipes" -a || echo "No changes to commit"
        git pull origin main --rebase
        git push origin main
