name: Remove Duplicates

on:
  workflow_run:
    workflows: ['ARM Weekly Python Scraper']
    types: 
      - completed
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Get current date
        id: date
        run: |
          echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Process CSV files
        run: |
          python script.py ${{ env.CSV_FILE_PATH1 }}
          python script.py ${{ env.CSV_FILE_PATH2 }}
        env:
          CSV_FILE_PATH1: ${{ github.workspace }}/data/scrapedData/foodBasics/foodbasics_${{ steps.date.outputs.date }}.csv
          CSV_FILE_PATH2: ${{ github.workspace }}/data/scrapedData/metro/metro_${{ steps.date.outputs.date }}.csv
