name: OpenAI Script

on:
    workflow_dispatch:
    workflow_run:
        workflows: ['ARM Weekly Python Scraper']
        types: [completed]
        branches:
            - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"

    - name: Run script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        CSV_FILE_PATH: data/scrapedData/metro/metro_${{ steps.date.outputs.date }}.csv
        NUM_RECIPES: 10
        TOTAL_COST: 25
        IS_VEGAN: false
        TOTAL_SERVINGS: 2
      run: python scripts/requestRecipes.py
