name: CURL to Endpoint

on:
  workflow_dispatch:

jobs:
  curl-job:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}       

      - name: Run CURL Command
        run: |
          curl -X GET http://172.30.1.6:9091
